### ISSUE TITLE
Geek Time

### ISSUE THREAD

**Issue by PaulChess** [PaulChess/fe-basic#30]
前端 Knowledge 一览:
  
![image](https://user-images.githubusercontent.com/69644161/157440497-30f9c8a7-17e0-408b-8899-b37536cdeee3.png)

**Comment by PaulChess** [comment]
vue3:
defineProps({})
defineEmists()

**Comment by PaulChess** [comment]
vue3的 `v-model`:
```javascript
let props = defineProps({ 
  modelValue: Number
})
let emits = defineEmits(['update:modelValue'])

// emit
function update(num) {
  emits('update:modelValue', num);
}
```

**Comment by PaulChess** [comment]
![image](https://user-images.githubusercontent.com/69644161/157616665-bd887937-3249-4d4c-a234-40a61abfc848.png)

**Comment by PaulChess** [comment]
**vue 动画**
```javascript
<transition name="fade">
  <h1 v-if="showTitle">你好 Vue3</h1>
</transition>
```
![image](https://user-images.githubusercontent.com/69644161/157650298-984e49b9-083b-415f-8da0-5524ad3f6f2b.png)

这里的 `v` 就是我们设置的 `name` 属性，  
标签在进入和离开的时候，会有 `fade-enter-active` 和 `fade-leave-active` 的 class，进入的开始和结束会有 `fade-enter-from` 和 `face-enter-to` 两个 class。

```css
/* 过程类 */
.fade-enter-active,
.fade-leave-active {
  transition: opacity .5s linear;
}

/* 关键节点类 */
.fade-enter-from,
.fade-leave-to {
  opacity: 0;  
}
```

**vue 路由动效**
basic code:
```javascript
<router-view v-slot="{ Component }">
  <transition name="fade" mode="out-in">
    <component :is="Component" />
  </transition>
</router-view>
```
```css
.fade-enter-active,
.fade-leave-active {
  transition: opacity .5s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0
}
```
[4 个 Vue 路由过渡动效](https://juejin.cn/post/6963205355702583303)
